from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('reportes/', views.reportes, name='reportes'),
    path('membresias/', views.membresias, name='membresias'),
    path('observaciones/', views.observaciones, name='observaciones'),
    path('entradas_salidas/', views.entradas_salidas, name='entradas_salidas'),
    path('reglamento/', views.reglamento, name='reglamento'),
    path('horario/', views.horario, name='horario'),
    path('actividades/', views.actividades, name='actividades'),
    path('entrenadores/', views.entrenadores, name='entrenadores'),
    path('acercade/', views.acercade, name='acercade'),
    path('gestion_usuarios/', views.gestion_usuarios, name='gestion_usuarios'),
    path('sesion/', views.sesion, name='sesion'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("registrar_ingreso/", views.registrar_ingreso, name="registrar_ingreso"),
    path("guardar_observacion/", views.guardar_observacion, name="guardar_observacion"),
    path("listar_observaciones/", views.listar_observaciones, name="listar_observaciones"),
    path('editar_observacion/', views.editar_observacion_view, name='editar_observacion'),
    path('eliminar_observacion/', views.eliminar_observacion_view, name='eliminar_observacion'),
    path("eliminar_usuario/", views.eliminar_usuario, name="eliminar_usuario"),
   path('administradores/', views.administradores, name='administradores'),
  path('crear_admin/', views.crear_admin, name='crear_admin'),
     path('buscar_admin/', views.buscar_admin, name='buscar_admin'),
      path('eliminar_admin/', views.eliminar_admin, name='eliminar_admin'),
path('editar_admin/', views.editar_admin, name='editar_admin'),
]